server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost/movie-service?createDatabaseIfNotExist=true&serverTimezone=UTC-3&useSSl=false
    username: root # substitua pelo seu usuário local
    password: fatima25

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
